### ISSUE TITLE
(ML) Visualize features (City Police)

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#106]
First, we need to create a data aggregation file similar to `ml/data/data_311.json` for the city police data. Then, graph the data using any program of your choice. Find interesting fields and comment the visualizations. @RitwikGupta can help you as you go. Here's the police blotter archive: https://data.wprdc.org/dataset/uniform-crime-reporting-data. Should be similar to #60

**Comment by dzheng256** [comment]
made a get_police_data.py that is literally get_311_data.py with the resource id changed. also made the data_police.json. should I PR that? not sure if it's necessary to have two .py files when the only difference is one line

**Comment by vonbearshark** [comment]
Yeah they're similar, but the distinction in what datasets are accessed is important. Should be two lines, because you want to write the the data to a different file, too, no?

**Comment by dzheng256** [comment]
right, it was two lines

**Comment by dzheng256** [comment]
heres some stuff, there's some other cool fields ill add graphs for
![image](https://cloud.githubusercontent.com/assets/13357787/22477191/280b5fee-e7b3-11e6-8d2c-5fcc34504f10.png)

**Comment by dzheng256** [comment]
@vonbearshark I used the resource id for police data in main.js.. Looking at timestamps, I think that's data from the past 30 days. Fixed and made a new PR.. dataset is significantly larger now lol

**Comment by vonbearshark** [comment]
Yeah there's a lot more requests than that, haha. I have the link to the WPRDC resource at the top of the Issue, but here's the id: `391942e2-25ef-43e4-8263-f8519fa8aada`

**Comment by dzheng256** [comment]
@vonbearshark For my PR I actually used `044f2016-1dfd-4ab0-bc1e-065da05fca2e` instead of that id, because it is for "UCR Coded" data, so that means it has already been processed and validated to meet Uniform Crime Reporting standards. I think the timestamps of UCR coded data go beyond the 2005-2015 range of the other dataset. Looks like it's 2005-2017 plus four random ones from 1989, 2002, 2003, and 2004

**Comment by dzheng256** [comment]
![image](https://cloud.githubusercontent.com/assets/13357787/22478145/bfbe2058-e7b6-11e6-85c4-f5e32894ca8b.png)
probably should plot average #requests by dividing by populations in those areas

**Comment by vonbearshark** [comment]
^I think that would be a good idea. I bet the WPRDC has some census data. It would be really accurate if it was corresponding to both the area and the population at that year in the census, but that's completely unnecessary, I think

**Comment by dzheng256** [comment]
@vonbearshark If I had population for every year I could figure out average number of requests per capita over time, but not sure where to find that. Also not sure if we really need that. Assuming all the populations have remained proportional to each other over time, I could just assume the populations have remained the same and calculate requests per capita use census data from one year.. @RitwikGupta any ideas?

**Comment by rgradeck** [comment]
Look here for Neighborhood data. https://data.wprdc.org/dataset/pgh 

Keep in mind that the 2010 is the latest reliable data you'll have at small geographic areas. Also important to note that daytime population can be very different from resident population. Crime rates for areas with lots of visitors and a much smaller number of residents (Oakland, Downtown, South Side Flats, etc) will look high even though people perceive them to be safe. There is no work-around for this. Probably best to note that rates are based on resident population and areas with a high number of visitors may have higher crime rates due to the way data is compiled, and also because there are more potential targets excluded from the denominator. 

One other note - crime stats for small areas vary greatly over time. We encourage data to be averaged over time to smooth these differences - for example, compare a 2014-16 average to a 2011-13 average to see if the neighborhood is becoming more safe.

**Comment by dzheng256** [comment]
@rgradeck Thanks! Some really good points.
