### ISSUE TITLE
WPRDC data: auto crash data analysis

### ISSUE THREAD

**Issue by vonbearshark** [Pitt-CSC/club_project_2017#67]
So the WPRDC does not provide live auto crash data afaik, but it _does_ provide historic auto crash data for the past 10 years. This seems like a perfect use case for ML. Maybe we could make a prediction for dangerous intersections or road areas that we can label on the map, then when we click on it, it can show all the accident history for that area. What do you think, @RitwikGupta? Data is here: https://data.wprdc.org/dataset/allegheny-county-crash-data

**Comment by pitchaim** [comment]
@vonbearshark Interested in assigning myself to this.

My idea would be to discretize crash/incident frequencies (maybe weighting each incident by severity) into danger tiers, and assign each intersection to a tier for labeling - anyone else have thoughts? @RitwikGupta? Could maybe separate auto and bike data, & toggle between them

**Comment by RitwikGupta** [comment]
I think this is cool! First step would be to analyze which fields are interesting first. Multiple fields could convey how dangerous an intersection is so analyzing all of them is very important first.

**Comment by vonbearshark** [comment]
For reference, here's the dictionary for the fields, so you can decipher the data: https://data.wprdc.org/dataset/allegheny-county-crash-data/resource/12d9e6e1-3657-4cad-a430-119d34b1a5b2. I don't think it's limited to just intersections, so it might be nice to have a general area analysis for each accident with overlap, rather than just an intersection. I'd definitely like to see bike data specifically called out. Would be great to use for #19

**Comment by RitwikGupta** [comment]
@pitchaim For now, you can use `wget "https://data.wprdc.org/api/action/datastore_search?resource_id=2c13021f-74a9-4289-a1e5-fe0472c89881&limit=144921" -O data.json` to get all the data (takes some time). I'll push a Python script later in the day.

**Comment by pitchaim** [comment]
@vonbearshark @RitwikGupta Sounds good - I'll pull & comb through the data for now. Definitely going to run some analysis on topography and incident fields, and let that dictate what risk level categorizing/weighting and region separation will look like. 

Also thinking it could be cool (at some point later) to pull time of day information and factor that into display, since rush hour peak times could be decent accident predictors.

**Comment by RitwikGupta** [comment]
I made this quick graph
![traffic](http://i.imgur.com/AFbNC9w.jpg)

**Comment by RitwikGupta** [comment]
I made a better graph, red line is mean, green lines are st. dev.
![traffic count](http://i.imgur.com/Z5w7FXA.jpg)

**Comment by RitwikGupta** [comment]
![belted unbelted deaths](http://i.imgur.com/uLXcfWX.jpg)

**Comment by brlodi** [comment]
@RitwikGupta does the dataset include any information on what percentage of roadways have a given speed limit? It might be interesting to normalize that ^ with that basis.

**Comment by RitwikGupta** [comment]
@brlodi Nope!

**Comment by pitchaim** [comment]
Sorry I'm taking some time on this - class, work, and python version hell, you know how it goes...
Scipy is finally up and running; still going through incident fields for now. 

Thought - once we establish some sort of classifier function mapping field values to danger tiers, we could look into relating that to other relevant, general data about streets/intersections that isn't accident-specific (like traffic volume, or whatever else WPRDC has) - my thinking is that we could try to predict accident risks in areas without any reported accidents, since (I'm assuming) there hasn't been one at every possible street chunk or intersection...

**Comment by RitwikGupta** [comment]
@pitchaim Exactly, but the important part is to first identify useful features.

**Comment by pitchaim** [comment]
Drunk driver incidence by time of day 

![dd_by_tod](https://cloud.githubusercontent.com/assets/17146250/22608924/e92b7288-ea2c-11e6-971c-733dd83e541b.png)

**Comment by pitchaim** [comment]
@vonbearshark @RitwikGupta working on comprehensive correlations table and a few more plots, will upload soon. How are we handling location for now? I've just arbitrarily filtered the data for lat/long within 1.5 miles of Cathy, do we have a better system in place?

**Comment by vonbearshark** [comment]
For the request for data we've been adding a SQL to find everything tagged as the Oakland neighborhood: https://github.com/Pitt-CSC/PantherView/blob/master/main.js#L227
